// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIntCircuitCtl wrapper class

class CIntCircuitCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIntCircuitCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x90bb18c2, 0xef5e, 0x11d1, { 0xb8, 0x90, 0xe9, 0xc, 0xf0, 0x92, 0x81, 0x2b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetBackColor(unsigned long newValue);
	unsigned long GetBackColor();
	long GetIsStockOK();
	short Count(LPCTSTR bstrName);
	short GetCountByIndex(short sIndex);
	void SetCountByIndex(short sIndex, short nNewValue);
};
