//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TaskManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TASKMATYPE                  129
#define IDD_DIALOG_REASON               130
#define IDC_EDIT_REASON                 1000
#define IDC_EDIT_TYPE                   1001
#define ID_JOB_NEW                      32771
#define ID_JOB_PAUSE                    32772
#define ID_JOB_OK                       32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
