#if !defined(AFX_TEAMROOM_H__6642B883_FB27_11D1_B890_B94569EB8B12__INCLUDED_)
#define AFX_TEAMROOM_H__6642B883_FB27_11D1_B890_B94569EB8B12__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CTeamRoom wrapper class

class CTeamRoom : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeamRoom)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd2df0e66, 0xdc6b, 0x11d1, { 0xb8, 0x90, 0x83, 0xb4, 0xb7, 0xf8, 0x0, 0x22 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	long GetArea();
	void SetArea(long);
	short GetCountRoom();
	void SetCountRoom(short);
	short GetCountOrderAll();
	void SetCountOrderAll(short);
	float GetSumOrderAll();
	void SetSumOrderAll(float);
	CString GetInfoOrderAll();
	void SetInfoOrderAll(LPCTSTR);

// Operations
public:
	BOOL Room(short x0, short y0, short x1, short y1, short xDoor, short yDoor);
	CString GetName(short sIndex);
	void SetName(short sIndex, LPCTSTR lpszNewValue);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEAMROOM_H__6642B883_FB27_11D1_B890_B94569EB8B12__INCLUDED_)
